import { DOMAINS, type ConfidenceLevel, type DomainKey, type MisconceptionType, type Scenario } from '../types/scenario.ts';
import type { Attempt, OverallReadiness } from '../types/attempt.ts';

export function calculateMisconceptionType(correct: boolean, confidence: ConfidenceLevel): MisconceptionType {
  if (correct) {
    if (confidence === 'confident') return 'strong_signal';
    if (confidence === 'guessing') return 'lucky_hit';
    return 'solid_understanding';
  } else {
    if (confidence === 'confident') return 'dangerous_misconception';
    if (confidence === 'fairly_sure') return 'needs_review';
    return 'knowledge_gap';
  }
}

export function generateStudyPlanMarkdown(
  readiness: OverallReadiness,
  scenarios: Scenario[],
  attempts: Map<string, Attempt>
): string {
  const dateStr = new Date().toISOString().split('T')[0];
  const dangerous = scenarios.filter(s => {
    const a = attempts.get(s.slug);
    return a && !a.correct && a.confidence === 'confident';
  });

  const gaps = scenarios.filter(s => {
    const a = attempts.get(s.slug);
    return a && !a.correct && a.confidence === 'guessing';
  });

  const needsReview = scenarios.filter(s => {
    const a = attempts.get(s.slug);
    return a && !a.correct && a.confidence === 'fairly_sure';
  });

  const lucky = scenarios.filter(s => {
    const a = attempts.get(s.slug);
    return a && a.correct && a.confidence === 'guessing';
  });

  const unattempted = scenarios.filter(s => !attempts.has(s.slug));
  const domainKeys: DomainKey[] = ['prepare_data', 'maintain_analytics', 'semantic_models'];

  let md = `# Fabric Triage: DP-600 Study Action Plan\n`;
  md += `**Date:** ${dateStr}  \n`;
  md += `**Practice Accuracy:** ${readiness.accuracyPercent !== null ? `${readiness.accuracyPercent}%` : 'Pending'} (${readiness.totalCorrect}/${readiness.totalAttempted} attempted)  \n`;
  md += `**Assessment Coverage:** ${readiness.coveragePercent}% (${readiness.totalAttempted}/${readiness.totalScenarios} incidents)  \n`;
  md += readiness.assessmentComplete
    ? `**Assessment Status:** All practice incidents triaged. This sample does not guarantee exam readiness.  \n\n`
    : `**Assessment Status:** Incomplete. Unattempted incidents are unknown evidence and are not counted as mastered.  \n\n`;

  md += `## Domain Breakdown\n`;
  for (const key of domainKeys) {
    const meta = DOMAINS[key];
    const stats = readiness.domainStats[key];
    const score = stats.scorePercent !== null ? `${stats.scorePercent}%` : 'Pending';
    md += `- **${meta.title} (${meta.examWeightRange} of exam):** ${score} accuracy (${stats.correctCount}/${stats.attemptedCount} attempted; ${stats.attemptedCount}/${stats.totalIncidents} coverage)\n`;
  }
  md += `\n`;

  md += `## Priority 1: Dangerous Misconceptions (High Confidence, Incorrect)\n`;
  if (dangerous.length === 0) {
    md += `*No high-confidence errors are present in the attempted cases.*\n\n`;
  } else {
    dangerous.forEach(s => {
      md += `### Case ${String(s.caseNumber).padStart(2, '0')}: ${s.title}\n`;
      md += `- **Domain:** ${s.domainLabel} (${s.skillArea})\n`;
      md += `- **Exam Takeaway:** ${s.examTakeaway}\n`;
      md += `- **Core Explanation:** ${s.explanation}\n\n`;
    });
  }

  md += `## Priority 2: Knowledge Gaps & Needs Review\n`;
  const p2 = [...needsReview, ...gaps];
  if (p2.length === 0) {
    md += `*No low- or mid-confidence errors are present in the attempted cases.*\n\n`;
  } else {
    p2.forEach(s => {
      const a = attempts.get(s.slug);
      const isReview = a?.confidence === 'fairly_sure';
      md += `- **Case ${String(s.caseNumber).padStart(2, '0')}: ${s.title}** [${isReview ? 'Needs Review' : 'Knowledge Gap'}] (${s.skillArea}): ${s.examTakeaway}\n`;
    });
    md += `\n`;
  }

  if (lucky.length > 0) {
    md += `## Priority 3: Lucky Hits (Correct Answer, Low Confidence)\n`;
    lucky.forEach(s => {
      md += `- **Case ${String(s.caseNumber).padStart(2, '0')}: ${s.title}** (${s.skillArea}): ${s.examTakeaway}\n`;
    });
    md += `\n`;
  }

  md += `## Unattempted Cases (${unattempted.length})\n`;
  if (unattempted.length === 0) {
    md += `*All practice incidents have been triaged.*\n\n`;
  } else {
    unattempted.forEach(s => {
      md += `- **Case ${String(s.caseNumber).padStart(2, '0')}: ${s.title}** (${s.skillArea})\n`;
    });
    md += `\n`;
  }

  md += `---\n`;
  md += `Confirm current scope and changes in the [official Microsoft Learn DP-600 study guide](https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/dp-600).\n\n`;
  md += `*Generated by Fabric Triage: DP-600 Incident Simulator.*`;
  return md;
}
